# fly.toml app configuration file generated for test-mgr on 2024-04-24T16:33:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-mgr'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
