name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/bnoon/tired-manager:${{ github.ref_name }}

    - name: Push to github repository
      run: VERSION=${{ github.ref_name }} docker push ghcr.io/bnoon/tired-manager:${{ github.ref_name }}
